// Initial welcome elements for the whiteboard
import type { WhiteboardElement } from './types';
import { generateId } from './engine';

export function createWelcomeElements(): WhiteboardElement[] {
  return [
    // Title text
    {
      id: generateId(),
      type: 'text',
      x: -150,
      y: -200,
      width: 400,
      height: 50,
      rotation: 0,
      color: '#1e1e1e',
      strokeWidth: 0,
      opacity: 1,
      fill: 'transparent',
      createdAt: Date.now(),
      text: '欢迎使用 Z-Board 白板',
      fontSize: 32,
      fontFamily: 'system-ui, sans-serif',
    } as WhiteboardElement,
    // Subtitle
    {
      id: generateId(),
      type: 'text',
      x: -150,
      y: -140,
      width: 400,
      height: 30,
      rotation: 0,
      color: '#8b8b8b',
      strokeWidth: 0,
      opacity: 1,
      fill: 'transparent',
      createdAt: Date.now(),
      text: '开始创作，尽情发挥想象力',
      fontSize: 18,
      fontFamily: 'system-ui, sans-serif',
    } as WhiteboardElement,
    // Sticky note 1
    {
      id: generateId(),
      type: 'sticky',
      x: -200,
      y: -50,
      width: 180,
      height: 160,
      rotation: 0,
      color: '#1e1e1e',
      strokeWidth: 1,
      opacity: 1,
      fill: '#fef3c7',
      createdAt: Date.now(),
      text: '使用左侧工具栏选择画笔、形状等工具',
      fontSize: 14,
      fontFamily: 'system-ui, sans-serif',
    } as WhiteboardElement,
    // Sticky note 2
    {
      id: generateId(),
      type: 'sticky',
      x: 20,
      y: -50,
      width: 180,
      height: 160,
      rotation: 0,
      color: '#1e1e1e',
      strokeWidth: 1,
      opacity: 1,
      fill: '#dbeafe',
      createdAt: Date.now(),
      text: '按住空格键拖拽可以平移画布，滚轮可以缩放',
      fontSize: 14,
      fontFamily: 'system-ui, sans-serif',
    } as WhiteboardElement,
    // Sticky note 3
    {
      id: generateId(),
      type: 'sticky',
      x: 240,
      y: -50,
      width: 180,
      height: 160,
      rotation: 0,
      color: '#1e1e1e',
      strokeWidth: 1,
      opacity: 1,
      fill: '#d1fae5',
      createdAt: Date.now(),
      text: 'Ctrl+Z 撤销，Ctrl+Y 重做，Delete 删除选中元素',
      fontSize: 14,
      fontFamily: 'system-ui, sans-serif',
    } as WhiteboardElement,
    // Decorative rectangle
    {
      id: generateId(),
      type: 'rectangle',
      x: -200,
      y: 150,
      width: 150,
      height: 100,
      rotation: 0,
      color: '#1c7ed6',
      strokeWidth: 2,
      opacity: 0.8,
      fill: '#dbeafe',
      borderRadius: 8,
      createdAt: Date.now(),
    } as WhiteboardElement,
    // Decorative circle
    {
      id: generateId(),
      type: 'circle',
      x: 10,
      y: 150,
      width: 120,
      height: 120,
      rotation: 0,
      color: '#2b8a3e',
      strokeWidth: 2,
      opacity: 0.8,
      fill: '#d1fae5',
      createdAt: Date.now(),
    } as WhiteboardElement,
    // Decorative diamond
    {
      id: generateId(),
      type: 'diamond',
      x: 180,
      y: 155,
      width: 110,
      height: 110,
      rotation: 0,
      color: '#e8590c',
      strokeWidth: 2,
      opacity: 0.8,
      fill: '#fed7aa',
      createdAt: Date.now(),
    } as WhiteboardElement,
    // Arrow from rectangle to circle
    {
      id: generateId(),
      type: 'arrow',
      x: -40,
      y: 195,
      width: 40,
      height: 5,
      rotation: 0,
      color: '#8b8b8b',
      strokeWidth: 2,
      opacity: 0.6,
      fill: 'transparent',
      createdAt: Date.now(),
      startX: -48,
      startY: 200,
      endX: 8,
      endY: 200,
    } as WhiteboardElement,
    // Arrow from circle to diamond
    {
      id: generateId(),
      type: 'arrow',
      x: 130,
      y: 200,
      width: 55,
      height: 5,
      rotation: 0,
      color: '#8b8b8b',
      strokeWidth: 2,
      opacity: 0.6,
      fill: 'transparent',
      createdAt: Date.now(),
      startX: 132,
      startY: 210,
      endX: 182,
      endY: 210,
    } as WhiteboardElement,
  ];
}
